name: Build and install

on:
  push:
    branches: [ "main" ]
  pull_request:
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: mymindstorm/setup-emsdk@v11
    - uses: actions/setup-node@v3
    - name: Build
      run: make
    - name: Run node test
      run: |
        cd js/test/node
        npm install
        npm run test
